-- Migration: v1.1.0
-- Description: Add nodes table placeholder
-- Created At: 2026-06-25

-- Example table structure for future nodes:
-- CREATE TABLE IF NOT EXISTS nodes (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     name VARCHAR NOT NULL,
--     ip VARCHAR NOT NULL,
--     port INTEGER,
--     api_key VARCHAR
-- );
